BOARD_SPACES = [
    {"pos": 0,  "name": "Go",                        "type": "go"},
    {"pos": 1,  "name": "Mediterranean Avenue",       "type": "property",
     "color": "brown",     "price": 60,  "house_cost": 50,
     "rent": [2, 4, 10, 30, 90, 160, 250]},
    {"pos": 2,  "name": "Community Chest",            "type": "community_chest"},
    {"pos": 3,  "name": "Baltic Avenue",              "type": "property",
     "color": "brown",     "price": 60,  "house_cost": 50,
     "rent": [4, 8, 20, 60, 180, 320, 450]},
    {"pos": 4,  "name": "Income Tax",                 "type": "tax", "amount": 200},
    {"pos": 5,  "name": "Reading Railroad",           "type": "railroad", "price": 200},
    {"pos": 6,  "name": "Oriental Avenue",            "type": "property",
     "color": "light_blue", "price": 100, "house_cost": 50,
     "rent": [6, 12, 30, 90, 270, 400, 550]},
    {"pos": 7,  "name": "Chance",                     "type": "chance"},
    {"pos": 8,  "name": "Vermont Avenue",             "type": "property",
     "color": "light_blue", "price": 100, "house_cost": 50,
     "rent": [6, 12, 30, 90, 270, 400, 550]},
    {"pos": 9,  "name": "Connecticut Avenue",         "type": "property",
     "color": "light_blue", "price": 120, "house_cost": 50,
     "rent": [8, 16, 40, 100, 300, 450, 600]},
    {"pos": 10, "name": "Just Visiting / Jail",       "type": "jail"},
    {"pos": 11, "name": "St. Charles Place",          "type": "property",
     "color": "pink",      "price": 140, "house_cost": 100,
     "rent": [10, 20, 50, 150, 450, 625, 750]},
    {"pos": 12, "name": "Electric Company",           "type": "utility", "price": 150},
    {"pos": 13, "name": "States Avenue",              "type": "property",
     "color": "pink",      "price": 140, "house_cost": 100,
     "rent": [10, 20, 50, 150, 450, 625, 750]},
    {"pos": 14, "name": "Virginia Avenue",            "type": "property",
     "color": "pink",      "price": 160, "house_cost": 100,
     "rent": [12, 24, 60, 180, 500, 700, 900]},
    {"pos": 15, "name": "Pennsylvania Railroad",      "type": "railroad", "price": 200},
    {"pos": 16, "name": "St. James Place",            "type": "property",
     "color": "orange",    "price": 180, "house_cost": 100,
     "rent": [14, 28, 70, 200, 550, 750, 950]},
    {"pos": 17, "name": "Community Chest",            "type": "community_chest"},
    {"pos": 18, "name": "Tennessee Avenue",           "type": "property",
     "color": "orange",    "price": 180, "house_cost": 100,
     "rent": [14, 28, 70, 200, 550, 750, 950]},
    {"pos": 19, "name": "New York Avenue",            "type": "property",
     "color": "orange",    "price": 200, "house_cost": 100,
     "rent": [16, 32, 80, 220, 600, 800, 1000]},
    {"pos": 20, "name": "Free Parking",               "type": "free_parking"},
    {"pos": 21, "name": "Kentucky Avenue",            "type": "property",
     "color": "red",       "price": 220, "house_cost": 150,
     "rent": [18, 36, 90, 250, 700, 875, 1050]},
    {"pos": 22, "name": "Chance",                     "type": "chance"},
    {"pos": 23, "name": "Indiana Avenue",             "type": "property",
     "color": "red",       "price": 220, "house_cost": 150,
     "rent": [18, 36, 90, 250, 700, 875, 1050]},
    {"pos": 24, "name": "Illinois Avenue",            "type": "property",
     "color": "red",       "price": 240, "house_cost": 150,
     "rent": [20, 40, 100, 300, 750, 925, 1100]},
    {"pos": 25, "name": "B&O Railroad",               "type": "railroad", "price": 200},
    {"pos": 26, "name": "Atlantic Avenue",            "type": "property",
     "color": "yellow",    "price": 260, "house_cost": 150,
     "rent": [22, 44, 110, 330, 800, 975, 1150]},
    {"pos": 27, "name": "Ventnor Avenue",             "type": "property",
     "color": "yellow",    "price": 260, "house_cost": 150,
     "rent": [22, 44, 110, 330, 800, 975, 1150]},
    {"pos": 28, "name": "Water Works",                "type": "utility", "price": 150},
    {"pos": 29, "name": "Marvin Gardens",             "type": "property",
     "color": "yellow",    "price": 280, "house_cost": 150,
     "rent": [24, 48, 120, 360, 850, 1025, 1200]},
    {"pos": 30, "name": "Go to Jail",                 "type": "go_to_jail"},
    {"pos": 31, "name": "Pacific Avenue",             "type": "property",
     "color": "green",     "price": 300, "house_cost": 200,
     "rent": [26, 52, 130, 390, 900, 1100, 1275]},
    {"pos": 32, "name": "North Carolina Avenue",      "type": "property",
     "color": "green",     "price": 300, "house_cost": 200,
     "rent": [26, 52, 130, 390, 900, 1100, 1275]},
    {"pos": 33, "name": "Community Chest",            "type": "community_chest"},
    {"pos": 34, "name": "Pennsylvania Avenue",        "type": "property",
     "color": "green",     "price": 320, "house_cost": 200,
     "rent": [28, 56, 150, 450, 1000, 1200, 1400]},
    {"pos": 35, "name": "Short Line Railroad",        "type": "railroad", "price": 200},
    {"pos": 36, "name": "Chance",                     "type": "chance"},
    {"pos": 37, "name": "Park Place",                 "type": "property",
     "color": "dark_blue", "price": 350, "house_cost": 200,
     "rent": [35, 70, 175, 500, 1100, 1300, 1500]},
    {"pos": 38, "name": "Luxury Tax",                 "type": "tax", "amount": 100},
    {"pos": 39, "name": "Boardwalk",                  "type": "property",
     "color": "dark_blue", "price": 400, "house_cost": 200,
     "rent": [50, 100, 200, 600, 1400, 1700, 2000]},
]

COLOR_GROUPS = {
    "brown":      [1, 3],
    "light_blue": [6, 8, 9],
    "pink":       [11, 13, 14],
    "orange":     [16, 18, 19],
    "red":        [21, 23, 24],
    "yellow":     [26, 27, 29],
    "green":      [31, 32, 34],
    "dark_blue":  [37, 39],
}

RAILROADS = [5, 15, 25, 35]
UTILITIES = [12, 28]

COLOR_HEX = {
    "brown":      "#8B4513",
    "light_blue": "#87CEEB",
    "pink":       "#FF69B4",
    "orange":     "#FFA500",
    "red":        "#FF4444",
    "yellow":     "#FFD700",
    "green":      "#228B22",
    "dark_blue":  "#00008B",
}

PLAYER_COLORS = ["#E74C3C", "#3498DB", "#2ECC71", "#F39C12"]
PLAYER_COLOR_NAMES = ["Red", "Blue", "Green", "Orange"]

CHANCE_CARDS = [
    {"id": 1,  "text": "Advance to Go! Collect $200.", "action": "advance_to", "target": 0},
    {"id": 2,  "text": "Advance to Illinois Avenue. If you pass Go, collect $200.", "action": "advance_to", "target": 24},
    {"id": 3,  "text": "Advance to St. Charles Place. If you pass Go, collect $200.", "action": "advance_to", "target": 11},
    {"id": 4,  "text": "Advance to nearest Railroad. Pay double rent if owned.", "action": "nearest_railroad"},
    {"id": 5,  "text": "Advance to nearest Railroad. Pay double rent if owned.", "action": "nearest_railroad"},
    {"id": 6,  "text": "Advance to nearest Utility. If owned, throw dice and pay 10x.", "action": "nearest_utility"},
    {"id": 7,  "text": "Bank pays you a dividend of $50.", "action": "collect", "amount": 50},
    {"id": 8,  "text": "Get Out of Jail Free.", "action": "get_out_of_jail_free"},
    {"id": 9,  "text": "Go Back 3 Spaces.", "action": "go_back", "amount": 3},
    {"id": 10, "text": "Go to Jail! Do not pass Go, do not collect $200.", "action": "go_to_jail"},
    {"id": 11, "text": "Make general repairs: $25/house, $100/hotel.", "action": "repairs", "house_cost": 25, "hotel_cost": 100},
    {"id": 12, "text": "Pay poor tax of $15.", "action": "pay", "amount": 15},
    {"id": 13, "text": "Take a trip to Reading Railroad. If you pass Go, collect $200.", "action": "advance_to", "target": 5},
    {"id": 14, "text": "Take a walk on the Boardwalk.", "action": "advance_to", "target": 39},
    {"id": 15, "text": "You have been elected Chairman of the Board. Pay each player $50.", "action": "pay_each_player", "amount": 50},
    {"id": 16, "text": "Your building and loan matures. Collect $150.", "action": "collect", "amount": 150},
]

COMMUNITY_CHEST_CARDS = [
    {"id": 1,  "text": "Advance to Go! Collect $200.", "action": "advance_to", "target": 0},
    {"id": 2,  "text": "Bank error in your favor. Collect $200.", "action": "collect", "amount": 200},
    {"id": 3,  "text": "Doctor fees. Pay $50.", "action": "pay", "amount": 50},
    {"id": 4,  "text": "From the sale of stock you get $50.", "action": "collect", "amount": 50},
    {"id": 5,  "text": "Get Out of Jail Free.", "action": "get_out_of_jail_free"},
    {"id": 6,  "text": "Go to Jail! Do not pass Go, do not collect $200.", "action": "go_to_jail"},
    {"id": 7,  "text": "Grand Opera Night. Collect $50 from every player.", "action": "collect_from_each", "amount": 50},
    {"id": 8,  "text": "Holiday Fund matures. Receive $100.", "action": "collect", "amount": 100},
    {"id": 9,  "text": "Income tax refund. Collect $20.", "action": "collect", "amount": 20},
    {"id": 10, "text": "It is your birthday! Collect $10 from every player.", "action": "collect_from_each", "amount": 10},
    {"id": 11, "text": "Life insurance matures. Collect $100.", "action": "collect", "amount": 100},
    {"id": 12, "text": "Pay hospital fees of $100.", "action": "pay", "amount": 100},
    {"id": 13, "text": "Pay school fees of $150.", "action": "pay", "amount": 150},
    {"id": 14, "text": "Receive $25 consultancy fee.", "action": "collect", "amount": 25},
    {"id": 15, "text": "Street repairs: $40/house, $115/hotel.", "action": "repairs", "house_cost": 40, "hotel_cost": 115},
    {"id": 16, "text": "You have won second prize in a beauty contest. Collect $10.", "action": "collect", "amount": 10},
]

SQUARE_ABBREV = {
    0: "GO", 1: "Mediterranean\nAve", 2: "Community\nChest", 3: "Baltic\nAve",
    4: "Income\nTax", 5: "Reading\nRR", 6: "Oriental\nAve", 7: "Chance",
    8: "Vermont\nAve", 9: "Connecticut\nAve", 10: "JAIL\nVisiting",
    11: "St. Charles\nPlace", 12: "Electric\nCo.", 13: "States\nAve",
    14: "Virginia\nAve", 15: "Penn.\nRR", 16: "St. James\nPlace",
    17: "Community\nChest", 18: "Tennessee\nAve", 19: "New York\nAve",
    20: "FREE\nPARKING", 21: "Kentucky\nAve", 22: "Chance", 23: "Indiana\nAve",
    24: "Illinois\nAve", 25: "B&O\nRR", 26: "Atlantic\nAve", 27: "Ventnor\nAve",
    28: "Water\nWorks", 29: "Marvin\nGardens", 30: "GO TO\nJAIL",
    31: "Pacific\nAve", 32: "N. Carolina\nAve", 33: "Community\nChest",
    34: "Penn.\nAve", 35: "Short Line\nRR", 36: "Chance", 37: "Park\nPlace",
    38: "Luxury\nTax", 39: "Boardwalk",
}

MAX_TURNS = 2000
STARTING_MONEY_DEFAULT = 1500
GO_SALARY = 200
JAIL_POSITION = 10
JAIL_FINE = 50
